package ctgu.awt.frame.homepage.component.anchor;

/**
 * Copyright © 2019 eSunny Info. Tech Ltd. All rights reserved.
 * 
 * 功能描述：
 * 
 * @Package: ctgu.awt.frame.homepage.component.anchor
 * @author: 拉布拉多
 */

public class Table {
	public static String table1 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"10px\" cellspacing=\"0\">\r\n"
			+ "            <tr>\r\n" + "                <th rowspan=\"2\">项目</th>\r\n"
			+ "                <th colspan=\"5\">土壤类别</th>\r\n" + "            </tr>\r\n" + "            <tr>\r\n"
			+ "                <th>特坚土</th>\r\n" + "                <th>坚土</th>\r\n"
			+ "                <th>次坚土</th>\r\n" + "                <th>普通土</th>\r\n"
			+ "                <th>软土</th>\r\n" + "            </tr>\r\n" + "            <tr>\r\n"
			+ "                <th>土壤名称</th>\r\n" + "                <td>风化岩或碎石土</td>\r\n"
			+ "                <td>黏土、黄土粗砂土</td>\r\n" + "                <td>亚黏土、亚砂土</td>\r\n"
			+ "                <td>粉土、粉砂土</td>\r\n" + "                <td>淤泥、填土</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                    <th>土壤状态</th>\r\n" + "                    <td>坚硬</td>\r\n"
			+ "                    <td>硬塑</td>\r\n" + "                    <td>硬塑</td>\r\n"
			+ "                    <td>可塑</td>\r\n" + "                    <td>软塑</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>含水状态</th>\r\n"
			+ "                    <td>干燥</td>\r\n" + "                    <td>稍湿</td>\r\n"
			+ "                    <td>中湿</td>\r\n" + "                    <td>较湿</td>\r\n"
			+ "                    <td>极湿</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>密实度</th>\r\n" + "                    <td>极密</td>\r\n"
			+ "                    <td>密实</td>\r\n" + "                    <td>中密</td>\r\n"
			+ "                    <td>稍密</td>\r\n" + "                    <td>维密</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>密度</th>\r\n"
			+ "                    <td>1900</td>\r\n" + "                    <td>1800</td>\r\n"
			+ "                    <td>1700</td>\r\n" + "                    <td>1600</td>\r\n"
			+ "                    <td>1500</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>计算抗拔角</th>\r\n" + "                    <td>30</td>\r\n"
			+ "                    <td>25</td>\r\n" + "                    <td>20</td>\r\n"
			+ "                    <td>15</td>\r\n" + "                    <td>10</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>凝聚力</th>\r\n"
			+ "                    <td></td>\r\n" + "                    <td>0.05</td>\r\n"
			+ "                    <td>0.04</td>\r\n" + "                    <td>0.02</td>\r\n"
			+ "                    <td>0.01</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>许可地耐力</th>\r\n" + "                    <td>0.5</td>\r\n"
			+ "                    <td>0.4</td>\r\n" + "                    <td>0.3</td>\r\n"
			+ "                    <td>0.2</td>\r\n" + "                    <td>0.1</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>开挖坡度（高：宽）</th>\r\n"
			+ "                    <td>1：0</td>\r\n" + "                    <td>1：0.15</td>\r\n"
			+ "                    <td>1：0.3</td>\r\n" + "                    <td>1：0.5</td>\r\n"
			+ "                    <td>1：0.75</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>简易判别法</th>\r\n" + "                    <td>镐难以掘近 需要爆破</td>\r\n"
			+ "                    <td>镐可以掘进 土壤成块状</td>\r\n" + "                    <td>镐易掘进 铲无法掘进</td>\r\n"
			+ "                    <td>一般不用镐 用铲同时用脚踩</td>\r\n" + "                    <td>用铲易掘进 无需脚踩</td>\r\n"
			+ "                </tr>\r\n" + "        </table><html>";

	public static String table2 = "<html>  <table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "            <tr>\r\n" + "                <th rowspan=\"2\">地埋木长度(cm)</th>\r\n"
			+ "                <th colspan=\"5\">地埋木直径(cm)</th>\r\n" + "            </tr>\r\n" + "            <tr>\r\n"
			+ "                <th>16</th>\r\n" + "                <th>18</th>\r\n" + "                <th>20</th>\r\n"
			+ "                <th>22</th>\r\n" + "                <th>24</th>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                    <th>100</th>\r\n" + "                    <td>34.65</td>\r\n"
			+ "                    <td>49.33</td>\r\n" + "                    <td>67.67</td>\r\n"
			+ "                    <td>90.08</td>\r\n" + "                    <td>116.94</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>120</th>\r\n"
			+ "                    <td>28.87</td>\r\n" + "                    <td>41.11</td>\r\n"
			+ "                    <td>56.40</td>\r\n" + "                    <td>75.06</td>\r\n"
			+ "                    <td>97.45</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>140</th>\r\n" + "                    <td>24.75</td>\r\n"
			+ "                    <td>35.24</td>\r\n" + "                    <td>48.34</td>\r\n"
			+ "                    <td>64.34</td>\r\n" + "                    <td>83.53</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>160</th>\r\n"
			+ "                    <td>31.66</td>\r\n" + "                    <td>30.83</td>\r\n"
			+ "                    <td>42.30</td>\r\n" + "                    <td>56.30</td>\r\n"
			+ "                    <td>79.09</td>\r\n" + "                </tr>\r\n" + "                <tr>\r\n"
			+ "                    <th>180</th>\r\n" + "                    <td>19.25</td>\r\n"
			+ "                    <td>27.41</td>\r\n" + "                    <td>37.60</td>\r\n"
			+ "                    <td>50.04</td>\r\n" + "                    <td>64.97</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>200</th>\r\n"
			+ "                    <td>17.32</td>\r\n" + "                    <td>24.67</td>\r\n"
			+ "                    <td>33.84</td>\r\n" + "                    <td>45.04</td>\r\n"
			+ "                    <td>58.47</td>\r\n" + "                </tr>\r\n" + "        </table></html>";
	public static String table3 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "            <tr>\r\n" + "                <th rowspan=\"2\">埋深 (m)</th>\r\n"
			+ "                <th>坚土</th>\r\n" + "                <th>次坚土</th>\r\n"
			+ "                <th>普通土</th>\r\n" + "                <th>软土</th>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>\r\n"
			+ "                    φ<sub>1</sub>=25<sup>°</sup> \r\n"
			+ "                    <p>γ<sub>0</sub>=1800</p>\r\n" + "                </th>\r\n"
			+ "                <th>\r\n" + "                        φ<sub>1</sub>=20<sup>°</sup> \r\n"
			+ "                        <p>γ<sub>0</sub>=1700</p>\r\n" + "                </th>\r\n"
			+ "                <th>\r\n" + "                        φ<sub>1</sub>=15<sup>°</sup> \r\n"
			+ "                        <p>γ<sub>0</sub>=1600</p>\r\n" + "                </th>\r\n"
			+ "                <th>\r\n" + "                        φ<sub>1</sub>=10<sup>°</sup> \r\n"
			+ "                        <p>γ<sub>0</sub>=1500</p>\r\n" + "                </th>\r\n"
			+ "            </tr>\r\n" + "            <tr>\r\n" + "                    <th>1.2</th>\r\n"
			+ "                    <td>27.11</td>\r\n" + "                    <td>20.12</td>\r\n"
			+ "                    <td>14.58</td>\r\n" + "                    <td>10.05</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.4</th>\r\n"
			+ "                    <td>37.25</td>\r\n" + "                    <td>27.19</td>\r\n"
			+ "                    <td>19.31</td>\r\n" + "                    <td>13.13</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.6</th>\r\n"
			+ "                    <td>49.46</td>\r\n" + "                    <td>35.58</td>\r\n"
			+ "                    <td>24.82</td>\r\n" + "                    <td>16.49</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.8</th>\r\n"
			+ "                    <td>63.91</td>\r\n" + "                    <td>45.41</td>\r\n"
			+ "                    <td>31.18</td>\r\n" + "                    <td>20.29</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>2.0</th>\r\n"
			+ "                    <td>80.78</td>\r\n" + "                    <td>56.76</td>\r\n"
			+ "                    <td>38.44</td>\r\n" + "                    <td>24.53</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>2.2</th>\r\n"
			+ "                    <td>101.5</td>\r\n" + "                    <td>69.74</td>\r\n"
			+ "                    <td>46.65</td>\r\n" + "                    <td>29.27</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>2.4</th>\r\n"
			+ "                    <td>123.8</td>\r\n" + "                    <td>84.85</td>\r\n"
			+ "                    <td>55.84</td>\r\n" + "                    <td>34.49</td>\r\n"
			+ "                </tr>\r\n" + "        </table></html>";
	public static String table4 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th rowspan=\"2\">埋深 (m)</th>\r\n"
			+ "            <th colspan=\"7\">地埋木规格（直径*长度，mm*mm）</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>∅16×120</th>\r\n" + "            <th>∅18×120</th>\r\n"
			+ "            <th>∅18×160</th>\r\n" + "            <th>∅18×180</th>\r\n"
			+ "            <th>∅20×120</th>\r\n" + "            <th>∅20×160</th>\r\n"
			+ "            <th>∅20×180</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th colspan=\"8\">坚土：φ<sub>1</sub>=25<sup>°</sup> ,γ<sub>0</sub>=1800</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.0</th>\r\n"
			+ "            <td>28.41</td>\r\n" + "            <td>29.26</td>\r\n" + "            <td>35.84</td>\r\n"
			+ "            <td>39.13</td>\r\n" + "            <td>30.11</td>\r\n" + "            <td>36.89</td>\r\n"
			+ "            <td>40.28</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.2</th>\r\n" + "            <td>41.86</td>\r\n" + "            <td>42.94</td>\r\n"
			+ "            <td>51.98</td>\r\n" + "            <td>56.49</td>\r\n" + "            <td>44.02</td>\r\n"
			+ "            <td>53.30</td>\r\n" + "            <td>57.94</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>1.4</th>\r\n" + "            <td>58.74</td>\r\n"
			+ "            <td>60.06</td>\r\n" + "            <td>71.93</td>\r\n" + "            <td>77.86</td>\r\n"
			+ "            <td>61.38</td>\r\n" + "            <td>73.53</td>\r\n" + "            <td>79.61</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.6</th>\r\n"
			+ "            <td>66.75</td>\r\n" + "            <td>80.96</td>\r\n" + "            <td>96.05</td>\r\n"
			+ "            <td>103.59</td>\r\n" + "            <td>82.55</td>\r\n" + "            <td>97.96</td>\r\n"
			+ "            <td>105.67</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.8</th>\r\n" + "            <td>83.40</td>\r\n" + "            <td>85.23</td>\r\n"
			+ "            <td>100.95</td>\r\n" + "            <td>134.04</td>\r\n" + "            <td>107.88</td>\r\n"
			+ "            <td>126.93</td>\r\n" + "            <td>136.46</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>2.0</th>\r\n" + "            <td>101.90</td>\r\n"
			+ "            <td>104.00</td>\r\n" + "            <td>126.25</td>\r\n" + "            <td>169.55</td>\r\n"
			+ "            <td>137.73</td>\r\n" + "            <td>160.80</td>\r\n" + "            <td>172.33</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th colspan=\"8\">次坚土：φ<sub>1</sub>=20<sup>°</sup> ,γ<sub>0</sub>=1700</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.0</th>\r\n"
			+ "            <td>20.76</td>\r\n" + "            <td>21.52</td>\r\n" + "            <td>26.75</td>\r\n"
			+ "            <td>29.36</td>\r\n" + "            <td>22.27</td>\r\n" + "            <td>27.69</td>\r\n"
			+ "            <td>30.40</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.2</th>\r\n" + "            <td>30.01</td>\r\n" + "            <td>30.96</td>\r\n"
			+ "            <td>38.08</td>\r\n" + "            <td>41.63</td>\r\n" + "            <td>31.90</td>\r\n"
			+ "            <td>39.25</td>\r\n" + "            <td>42.93</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>1.4</th>\r\n" + "            <td>41.44</td>\r\n"
			+ "            <td>42.59</td>\r\n" + "            <td>51.87</td>\r\n" + "            <td>56.52</td>\r\n"
			+ "            <td>43.74</td>\r\n" + "            <td>53.29</td>\r\n" + "            <td>58.07</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.6</th>\r\n"
			+ "            <td>55.24</td>\r\n" + "            <td>56.62</td>\r\n" + "            <td>68.35</td>\r\n"
			+ "            <td>74.21</td>\r\n" + "            <td>57.99</td>\r\n" + "            <td>70.03</td>\r\n"
			+ "            <td>76.04</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.8</th>\r\n" + "            <td>71.63</td>\r\n" + "            <td>73.24</td>\r\n"
			+ "            <td>87.69</td>\r\n" + "            <td>94.90</td>\r\n" + "            <td>74.84</td>\r\n"
			+ "            <td>89.65</td>\r\n" + "            <td>97.05</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>2.0</th>\r\n" + "            <td>90.81</td>\r\n"
			+ "            <td>92.66</td>\r\n" + "            <td>110.12</td>\r\n" + "            <td>118.85</td>\r\n"
			+ "            <td>94.52</td>\r\n" + "            <td>112.36</td>\r\n" + "            <td>121.29</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th colspan=\"8\">普通土：φ<sub>1</sub>=15<sup>°</sup> ,γ<sub>0</sub>=1600</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.0</th>\r\n"
			+ "            <td>14.76</td>\r\n" + "            <td>15.42</td>\r\n" + "            <td>19.48</td>\r\n"
			+ "            <td>21.50</td>\r\n" + "            <td>16.08</td>\r\n" + "            <td>20.32</td>\r\n"
			+ "            <td>22.44</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.2</th>\r\n" + "            <td>20.83</td>\r\n" + "            <td>21.66</td>\r\n"
			+ "            <td>27.10</td>\r\n" + "            <td>29.83</td>\r\n" + "            <td>22.48</td>\r\n"
			+ "            <td>28.15</td>\r\n" + "            <td>30.98</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>1.4</th>\r\n" + "            <td>28.19</td>\r\n"
			+ "            <td>29.19</td>\r\n" + "            <td>36.22</td>\r\n" + "            <td>39.74</td>\r\n"
			+ "            <td>30.18</td>\r\n" + "            <td>37.47</td>\r\n" + "            <td>41.12</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.6</th>\r\n"
			+ "            <td>36.93</td>\r\n" + "            <td>38.11</td>\r\n" + "            <td>46.93</td>\r\n"
			+ "            <td>51.33</td>\r\n" + "            <td>39.29</td>\r\n" + "            <td>48.40</td>\r\n"
			+ "            <td>52.95</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>1.8</th>\r\n" + "            <td>47.17</td>\r\n" + "            <td>48.54</td>\r\n"
			+ "            <td>59.33</td>\r\n" + "            <td>64.72</td>\r\n" + "            <td>49.91</td>\r\n"
			+ "            <td>61.03</td>\r\n" + "            <td>66.58</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>2.0</th>\r\n" + "            <td>72.53</td>\r\n"
			+ "            <td>74.31</td>\r\n" + "            <td>89.64</td>\r\n" + "            <td>97.30</td>\r\n"
			+ "            <td>76.10</td>\r\n" + "            <td>91.82</td>\r\n" + "            <td>99.68</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th colspan=\"8\">软土：φ<sub>1</sub>=10<sup>°</sup> ,γ<sub>0</sub>=1500</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "                <th>1.0</th>\r\n"
			+ "                <td>10.04</td>\r\n" + "                <td>10.62</td>\r\n"
			+ "                <td>13.65</td>\r\n" + "                <td>15.16</td>\r\n"
			+ "                <td>11.21</td>\r\n" + "                <td>14.40</td>\r\n"
			+ "                <td>15.60</td>\r\n" + "            </tr>\r\n" + "            <tr>\r\n"
			+ "                <th>1.2</th>\r\n" + "                <td>13.73</td>\r\n"
			+ "                <td>14.45</td>\r\n" + "                <td>18.44</td>\r\n"
			+ "                <td>20.43</td>\r\n" + "                <td>15.17</td>\r\n"
			+ "                <td>19.36</td>\r\n" + "                <td>21.46</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>1.4</th>\r\n" + "                <td>18.09</td>\r\n"
			+ "                <td>18.95</td>\r\n" + "                <td>24.02</td>\r\n"
			+ "                <td>26.55</td>\r\n" + "                <td>19.80</td>\r\n"
			+ "                <td>25.11</td>\r\n" + "                <td>27.77</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>1.6</th>\r\n" + "                <td>23.14</td>\r\n"
			+ "                <td>24.15</td>\r\n" + "                <td>30.42</td>\r\n"
			+ "                <td>33.56</td>\r\n" + "                <td>25.15</td>\r\n"
			+ "                <td>31.70</td>\r\n" + "                <td>34.97</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>1.8</th>\r\n" + "                <td>28.94</td>\r\n"
			+ "                <td>30.10</td>\r\n" + "                <td>37.70</td>\r\n"
			+ "                <td>41.50</td>\r\n" + "                <td>31.26</td>\r\n"
			+ "                <td>39.16</td>\r\n" + "                <td>43.11</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>2.0</th>\r\n" + "                <td>35.53</td>\r\n"
			+ "                <td>36.85</td>\r\n" + "                <td>45.89</td>\r\n"
			+ "                <td>50.41</td>\r\n" + "                <td>38.16</td>\r\n"
			+ "                <td>47.54</td>\r\n" + "                <td>52.23</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>2.2</th>\r\n" + "                <td>51.23</td>\r\n"
			+ "                <td>52.89</td>\r\n" + "                <td>65.17</td>\r\n"
			+ "                <td>71.81</td>\r\n" + "                <td>54.54</td>\r\n"
			+ "                <td>67.23</td>\r\n" + "                <td>73.58</td>\r\n" + "            </tr>\r\n"
			+ "    </table></html>";
	public static String table5 = "<html> <table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th rowspan=\"2\">型号</th>\r\n"
			+ "            <th colspan=\"4\">主要尺寸 (mm)</th>\r\n" + "            <th rowspan=\"2\">容许拉力 (kN)</th>\r\n"
			+ "            <th rowspan=\"2\">质量 (kg)</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>d</th>\r\n" + "            <th>l</th>\r\n" + "            <th>l<sub>1</sub></th>\r\n"
			+ "            <th>H</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "                <th>FM-1</th>\r\n" + "                <td>28</td>\r\n"
			+ "                <td>1000</td>\r\n" + "                <td>200</td>\r\n"
			+ "                <td>180</td>\r\n" + "                <td>49</td>\r\n" + "                <td>18</td>\r\n"
			+ "            </tr>\r\n" + "            <tr>\r\n" + "                <th>FM-2</th>\r\n"
			+ "                <td>30</td>\r\n" + "                <td>1100</td>\r\n"
			+ "                <td>250</td>\r\n" + "                <td>200</td>\r\n"
			+ "                <td>78.5</td>\r\n" + "                <td>20</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>FM-3</th>\r\n" + "                <td>38</td>\r\n"
			+ "                <td>1100</td>\r\n" + "                <td>300</td>\r\n"
			+ "                <td>230</td>\r\n" + "                <td>147.1</td>\r\n"
			+ "                <td>23</td>\r\n" + "            </tr>\r\n" + "    </table></html>";
	public static String table6 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th rowspan=\"2\">型号</th>\r\n"
			+ "            <th colspan=\"4\">主要尺寸 (mm)</th>\r\n" + "            <th rowspan=\"2\">容许拉力 (kN)</th>\r\n"
			+ "            <th rowspan=\"2\">备注</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>d</th>\r\n" + "            <th>l</th>\r\n" + "            <th>B</th>\r\n"
			+ "            <th>H</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n" + "            <th>CM-1</th>\r\n"
			+ "            <td>20</td>\r\n" + "            <td>600</td>\r\n" + "            <td>150</td>\r\n"
			+ "            <td>60</td>\r\n" + "            <td>29.4</td>\r\n" + "            <td></td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>CM-2</th>\r\n" + "            <td>20</td>\r\n"
			+ "            <td>800</td>\r\n" + "            <td>200</td>\r\n" + "            <td>80</td>\r\n"
			+ "            <td>34.3</td>\r\n" + "            <td></td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>CM-3</th>\r\n" + "            <td>22</td>\r\n" + "            <td>1000</td>\r\n"
			+ "            <td>250</td>\r\n" + "            <td>100</td>\r\n" + "            <td>44.1</td>\r\n"
			+ "            <td></td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n" + "            <th>CM-4</th>\r\n"
			+ "            <td>24</td>\r\n" + "            <td>1200</td>\r\n" + "            <td>300</td>\r\n"
			+ "            <td>140</td>\r\n" + "            <td>49.0</td>\r\n" + "            <td></td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>CM-5</th>\r\n" + "            <td>24</td>\r\n"
			+ "            <td>1200</td>\r\n" + "            <td>300</td>\r\n" + "            <td>140</td>\r\n"
			+ "            <td>78.5</td>\r\n" + "            <td>加强型</td>\r\n" + "        </tr>\r\n"
			+ "        <tr>\r\n" + "            <th>CM-6</th>\r\n" + "            <td>26</td>\r\n"
			+ "            <td>1500</td>\r\n" + "            <td>375</td>\r\n" + "            <td>160</td>\r\n"
			+ "            <td>83.4</td>\r\n" + "            <td>加强型</td>\r\n" + "        </tr>\r\n"
			+ "    </table></html>";
	public static String table7 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th rowspan=\"2\">型号</th>\r\n"
			+ "            <th colspan=\"4\">规格尺寸 (mm)</th>\r\n" + "            <th rowspan=\"2\">额定载荷 (kN)</th>\r\n"
			+ "            <th rowspan=\"2\">极限拔力 (kN)</th>\r\n" + "            <th rowspan=\"2\">适用土制条件</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>钻杆外径</th>\r\n"
			+ "            <th>钻杆长度L</th>\r\n" + "            <th>钻叶外径∅</th>\r\n" + "            <th>钻叶钢板厚</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "                <th>SDZ-1</th>\r\n"
			+ "                <td>40</td>\r\n" + "                <td>1200</td>\r\n"
			+ "                <td>220</td>\r\n" + "                <td>5</td>\r\n" + "                <td>10</td>\r\n"
			+ "                <td>20</td>\r\n" + "                <td>砂质土</td>\r\n" + "            </tr>\r\n"
			+ "            <tr>\r\n" + "                <th>SDZ-2</th>\r\n" + "                <td>40</td>\r\n"
			+ "                <td>1700</td>\r\n" + "                <td>250</td>\r\n"
			+ "                <td>5</td>\r\n" + "                <td>30</td>\r\n" + "                <td>60</td>\r\n"
			+ "                <td>砂质土</td>\r\n" + "            </tr>\r\n" + "            <tr>\r\n"
			+ "                <th>SDZ-3</th>\r\n" + "                <td>40</td>\r\n"
			+ "                <td>1700</td>\r\n" + "                <td>250</td>\r\n"
			+ "                <td>8</td>\r\n" + "                <td>50</td>\r\n" + "                <td>100</td>\r\n"
			+ "                <td>砂质土</td>\r\n" + "            </tr>\r\n" + "    </table></html>";
	public static String table8 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "            <tr>\r\n" + "                    <th>h(m)</th>\r\n"
			+ "                    <th>坚土 【σ】<sub>T</sub>=0.4</th>\r\n"
			+ "                    <th>次坚土【σ】<sub>T</sub>=0.3</th>\r\n"
			+ "                    <th>普通土【σ】<sub>T</sub>=0.2</th>\r\n"
			+ "                    <th>软土 【σ】<sub>T</sub>=0.1</th>\r\n" + "                </tr>\r\n"
			+ "                <tr>\r\n" + "                    <th>0.8</th>\r\n"
			+ "                    <td>6.787</td>\r\n" + "                    <td>5.09</td>\r\n"
			+ "                    <td>3.39</td>\r\n" + "                    <td>1.70</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.0</th>\r\n"
			+ "                    <td>8.484</td>\r\n" + "                    <td>6.36</td>\r\n"
			+ "                    <td>4.24</td>\r\n" + "                    <td>2.12</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.2</th>\r\n"
			+ "                    <td>10.181</td>\r\n" + "                    <td>7.64</td>\r\n"
			+ "                    <td>5.09</td>\r\n" + "                    <td>2.55</td>\r\n"
			+ "                </tr>\r\n" + "                <tr>\r\n" + "                    <th>1.4</th>\r\n"
			+ "                    <td>11.878</td>\r\n" + "                    <td>8.91</td>\r\n"
			+ "                    <td>5.94</td>\r\n" + "                    <td>2.97</td>\r\n"
			+ "                </tr>\r\n" + "    </table></html>";
	public static String table9 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th>土质类别</th>\r\n" + "            <th>单桩</th>\r\n"
			+ "            <th>双联桩</th>\r\n" + "            <th>三联桩</th>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>坚土</th>\r\n" + "            <td>8.5</td>\r\n" + "            <td>15.0</td>\r\n"
			+ "            <td>21.0</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>次坚土</th>\r\n" + "            <td>6.4</td>\r\n" + "            <td>12.0</td>\r\n"
			+ "            <td>16.0</td>\r\n" + "        </tr>\r\n" + "        <tr>\r\n"
			+ "            <th>普通土</th>\r\n" + "            <td>4.3</td>\r\n" + "            <td>8.0</td>\r\n"
			+ "            <td>10.0</td>\r\n" + "        </tr>\r\n" + "    </table></html>";
	public static String table10 = "<html><table style=\"text-align: center;\" border=\"1\" cellpadding=\"20px\" cellspacing=\"0\">\r\n"
			+ "        <tr>\r\n" + "            <th>h (m)</th>\r\n" + "            <th>坚土</th>\r\n"
			+ "            <th>次坚土</th>\r\n" + "            <th>普通图</th>\r\n" + "            <th>软土</th>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>0.8</th>\r\n" + "            <td>3.2</td>\r\n"
			+ "            <td>2.4</td>\r\n" + "            <td>1.6</td>\r\n" + "            <td>0.8</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.0</th>\r\n" + "            <td>4.0</td>\r\n"
			+ "            <td>3.0</td>\r\n" + "            <td>2.0</td>\r\n" + "            <td>1.0</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.2</th>\r\n" + "            <td>4.8</td>\r\n"
			+ "            <td>3.6</td>\r\n" + "            <td>2.4</td>\r\n" + "            <td>1.2</td>\r\n"
			+ "        </tr>\r\n" + "        <tr>\r\n" + "            <th>1.4</th>\r\n" + "            <td>5.6</td>\r\n"
			+ "            <td>4.2</td>\r\n" + "            <td>2.8</td>\r\n" + "            <td>1.4</td>\r\n"
			+ "        </tr>\r\n" + "    </table></html>";
}
